### ISSUE TITLE
the source code is incomplete.

### ISSUE THREAD

**Issue by hanshumin001** [sail-sg/ptp#1]
Hi, I am interesting in your method and find that the source code in incomplete. Can you upload  a new version code ?

I am looking forward your reply. Thank you very much.

**Comment by FingerRec** [comment]
Hi, the pre-training code and evaluation code based on ViLT is in cleaning up now. (as we showed in the update)

**Comment by hanshumin001** [comment]
HI，I can't find the script pretrain_concated_pred_tsv.py in the blip_src  folder.  Please check you flip  pre-training code, maybe there are some files missing. Thank you very mach.

**Comment by hanshumin001** [comment]
hi, ok ,thank you for your replay. I want to know when the pre-training
code will be released ?

shumin

Jinpeng Wang ***@***.***> 于2022年12月20日周二 17:54写道：

**Comment by FingerRec** [comment]
Hi hanshu:
The pre-training code will be released in the next two months. :)
