### ISSUE TITLE
Pre-exacted Image Feature for Visual Genome(VG)

### ISSUE THREAD

**Issue by 9115jin** [sail-sg/ptp#7]
Hello,

I'm currently in the process of re-implementing ptp-blip for my research in the field. However, I encountered an issue during the second step mentioned in ptp/DATASET.md, which is "2. Download/Prepare Corpus (image-text pair)." Following the instructions provided, I was able to download object features for COCO2014 train/val/test, 2015 test, CC3M, and SBU using the provided download_cc3m_predictions.sh script. However, I couldn't find a download link for VG (Visual Genome) and I'm currently searching for it.

If you happen to know the download link for VG or if image features for VG are not required separately, it would be immensely helpful if you could let me know. Once again, I want to express my gratitude for the excellent research work done with ptp.

Thank you!

* Here is a screenshot from the oscar website showing that there is no download link available for VG's image features.

![image](https://user-images.githubusercontent.com/28249978/234788393-7d6edd6a-e260-4b18-a657-5529970049cd.png)
![image](https://user-images.githubusercontent.com/28249978/234788608-dcfbfc53-00c8-40d9-accb-2c04efd0af79.png)

**Comment by FingerRec** [comment]
Hi Jin.

For the VG, the image feature is not provided.

Follow "https://github.com/FingerRec/OA-Transformer/blob/main/ObjectExtractor/multiprocess_full_cc3m_complementary_modify_tsv_gen_from_video.py" or BUTD (https://github.com/MILVLG/bottom-up-attention.pytorch/blob/master/extract_features.py)  implementation in to generate vg feature.

**Comment by 9115jin** [comment]
Hi FingerRec,

Thank you for the code to extract the image features for VG. I didn't realize there was a code available for that, so I appreciate you letting me know and sharing the link. Thanks a lot!
